<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Customer;
use App\Models\Employee;
use App\Models\Reservation;

class TestAutoGeneratedIdsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create test users
        $user1 = User::create([
            'username' => 'testuser1',
            'password' => bcrypt('password'),
            'role' => 'customer',
        ]);

        $user2 = User::create([
            'username' => 'testuser2',
            'password' => bcrypt('password'),
            'role' => 'employee',
        ]);

        // Create test customer
        $customer = Customer::create([
            'user_id' => $user1->user_id,
            'fullname' => 'Test Customer',
            'email' => 'customer@test.com',
            'phone_number' => '1234567890',
        ]);

        // Create test employee
        $employee = Employee::create([
            'user_id' => $user2->user_id,
            'fullname' => 'Test Employee',
            'email' => 'employee@test.com',
            'phone_number' => '0987654321',
            'hire_date' => now(),
            'position' => 'Staff',
        ]);

        // Create test reservation
        $reservation = Reservation::create([
            'customer_id' => $customer->customer_id,
            'items' => [
                [
                    'product_id' => 1,
                    'product_name' => 'Test Shoe',
                    'size' => '42',
                    'quantity' => 1,
                    'price' => 100.00
                ]
            ],
            'total_amount' => 100.00,
            'pickup_date' => now()->addDays(3),
            'pickup_time' => '14:00:00',
            'status' => 'pending',
            'notes' => 'Test reservation with auto-generated IDs',
        ]);

        echo "Created test data with auto-generated IDs:\n";
        echo "User 1 ID: {$user1->user_id}\n";
        echo "User 2 ID: {$user2->user_id}\n";
        echo "Customer ID: {$customer->customer_id}\n";
        echo "Employee ID: {$employee->employee_id}\n";
        echo "Reservation ID: {$reservation->reservation_id}\n";
    }
}
