<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Notifications\Notifiable;
use App\Traits\HasAutoGeneratedId;

class Customer extends Authenticatable
{
    use HasFactory, Notifiable, HasAutoGeneratedId;

    protected $primaryKey = 'customer_id';

    /**
     * Get the prefix for the auto-generated ID.
     */
    protected function getIdPrefix(): string
    {
        return 'CUST';
    }

    /**
     * Get the total length of the auto-generated ID.
     */
    protected function getIdLength(): int
    {
        return 15;
    }

    protected $fillable = [
        'user_id',
        'fullname',
        'email',
        'phone_number',
        'email_verification_code',
        'email_verification_code_expires_at',
        'email_verified_at',
        'is_restricted',
        'restricted_until',
        'restriction_reason',
        'restricted_by',
        'restricted_at',
    ];

    protected $hidden = [
        'email_verification_code',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'email_verification_code_expires_at' => 'datetime',
        'restricted_until' => 'datetime',
        'restricted_at' => 'datetime',
        'is_restricted' => 'boolean',
    ];

    /**
     * Get the password for authentication (from linked user)
     */
    public function getAuthPassword()
    {
        return $this->user ? $this->user->password : null;
    }

    /**
     * Get the username for authentication (use email)
     */
    public function getAuthIdentifierName()
    {
        return 'email';
    }

    /**
     * Get the unique identifier for authentication
     */
    public function getAuthIdentifier()
    {
        return $this->email;
    }

    /**
     * Get the remember token (from linked user)
     */
    public function getRememberToken()
    {
        return $this->user ? $this->user->getRememberToken() : null;
    }

    /**
     * Set the remember token (on linked user)
     */
    public function setRememberToken($value)
    {
        if ($this->user) {
            $this->user->setRememberToken($value);
            $this->user->save();
        }
    }

    /**
     * Get the remember token name (delegate to user)
     */
    public function getRememberTokenName()
    {
        return 'remember_token';
    }

    /**
     * Check if customer email is verified
     */
    public function hasVerifiedEmail()
    {
        return !is_null($this->email_verified_at);
    }

    /**
     * Mark customer email as verified
     */
    public function markEmailAsVerified()
    {
        $this->email_verified_at = now();
        $this->email_verification_code = null;
        $this->email_verification_code_expires_at = null;
        $this->save();
    }

    /**
     * Generate email verification code
     */
    public function generateEmailVerificationCode()
    {
        $this->email_verification_code = str_pad(random_int(0, 999999), 6, '0', STR_PAD_LEFT);
        $this->email_verification_code_expires_at = now()->addMinutes(10);
        $this->save();
        
        return $this->email_verification_code;
    }

    /**
     * Get the user that owns the customer.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id', 'user_id');
    }

    /**
     * Get the reservations for this customer.
     */
    public function reservations(): HasMany
    {
        return $this->hasMany(Reservation::class, 'customer_id', 'customer_id');
    }

    /**
     * Get the transactions for this customer through reservations.
     */
    public function transactions()
    {
        return Transaction::whereHas('reservation', function($query) {
            $query->where('customer_id', $this->customer_id);
        });
    }

    /**
     * Scope for active customers (based on user's is_active status)
     */
    public function scopeActive($query)
    {
        return $query->whereHas('user', function ($q) {
            $q->where('is_active', true);
        });
    }

    /**
     * Get customer's formatted name for display
     */
    public function getDisplayNameAttribute()
    {
        return $this->fullname;
    }

    /**
     * Get customer's contact information
     */
    public function getContactInfoAttribute()
    {
        $info = [];
        if ($this->email) $info[] = $this->email;
        if ($this->phone_number) $info[] = $this->phone_number;
        return implode(' • ', $info);
    }

    /**
     * Check if customer account is currently restricted
     */
    public function isRestricted()
    {
        if (!$this->is_restricted) {
            return false;
        }

        // If restricted_until is null, it's a permanent restriction
        if (is_null($this->restricted_until)) {
            return true;
        }

        // Check if restriction period has expired
        if ($this->restricted_until->isPast()) {
            // Auto-lift expired restrictions
            $this->liftRestriction();
            return false;
        }

        return true;
    }

    /**
     * Restrict customer account
     */
    public function restrict($days = null, $reason = null, $restrictedBy = null)
    {
        $this->is_restricted = true;
        $this->restricted_until = $days ? now()->addDays($days) : null;
        $this->restriction_reason = $reason;
        $this->restricted_by = $restrictedBy;
        $this->restricted_at = now();
        $this->save();
    }

    /**
     * Lift restriction from customer account
     */
    public function liftRestriction()
    {
        $this->is_restricted = false;
        $this->restricted_until = null;
        $this->restriction_reason = null;
        $this->restricted_by = null;
        $this->restricted_at = null;
        $this->save();
    }

    /**
     * Get days remaining in restriction
     */
    public function getDaysRemainingAttribute()
    {
        if (!$this->isRestricted() || is_null($this->restricted_until)) {
            return null;
        }

        return max(0, now()->diffInDays($this->restricted_until, false));
    }

    /**
     * Scope for non-restricted customers
     */
    public function scopeNotRestricted($query)
    {
        return $query->where(function($q) {
            $q->where('is_restricted', false)
              ->orWhere('restricted_until', '<', now());
        });
    }

    /**
     * Scope for restricted customers
     */
    public function scopeRestricted($query)
    {
        return $query->where('is_restricted', true)
                    ->where(function($q) {
                        $q->whereNull('restricted_until')
                          ->orWhere('restricted_until', '>=', now());
                    });
    }

    /**
     * Check if customer account is temporarily locked
     */
    public function isLocked()
    {
        return $this->isRestricted() && 
               $this->restriction_reason && 
               str_starts_with($this->restriction_reason, '[LOCKED]');
    }

    /**
     * Get lock status for UI display
     */
    public function getLockStatusAttribute()
    {
        if ($this->isLocked()) {
            if ($this->restricted_until) {
                $daysRemaining = $this->days_remaining;
                return "Locked for {$daysRemaining} more days";
            } else {
                return "Permanently locked";
            }
        }
        return null;
    }
}
