<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use App\Traits\HasAutoGeneratedId;

class Employee extends Model
{
    use HasFactory, HasAutoGeneratedId;

    protected $primaryKey = 'employee_id';

    /**
     * Get the prefix for the auto-generated ID.
     */
    protected function getIdPrefix(): string
    {
        return 'EMP';
    }

    /**
     * Get the total length of the auto-generated ID.
     */
    protected function getIdLength(): int
    {
        return 15;
    }

    protected $fillable = [
        'user_id',
        'fullname',
        'email',
        'phone_number',
        'hire_date',
        'position',
        'profile_picture',
    ];

    protected $casts = [
        'hire_date' => 'date',
    ];

    /**
     * Get the user that owns the employee.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id', 'user_id');
    }

    /**
     * Get the employee's formatted hire date
     */
    public function getFormattedHireDateAttribute()
    {
        return $this->hire_date ? $this->hire_date->format('M d, Y') : null;
    }

    /**
     * Get the employee's profile picture URL
     */
    public function getProfilePictureUrlAttribute()
    {
        if ($this->profile_picture && !str_starts_with($this->profile_picture, 'http')) {
            return asset($this->profile_picture);
        }
        return $this->profile_picture ?: asset('assets/images/default-profile.png');
    }

    /**
     * Scope for active employees (based on user's is_active status)
     */
    public function scopeActive($query)
    {
        return $query->whereHas('user', function ($q) {
            $q->where('is_active', true);
        });
    }

    /**
     * Scope for employees by position
     */
    public function scopeByPosition($query, $position)
    {
        return $query->where('position', $position);
    }
}
