<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use App\Traits\HasAutoGeneratedId;

class Reservation extends Model
{
    use HasAutoGeneratedId;

    protected $primaryKey = 'reservation_id';

    /**
     * Get the prefix for the auto-generated ID.
     */
    protected function getIdPrefix(): string
    {
        return 'RSV';
    }

    /**
     * Get the total length of the auto-generated ID.
     */
    protected function getIdLength(): int
    {
        return 15;
    }
    protected $fillable = [
        'reservation_id',
        'customer_id', // Foreign key to customers table
        'items', // JSON field for multiple products
        'total_amount',
        'pickup_date',
        'pickup_time',
        'status',
        'notes',
        'reserved_at'
    ];

    protected $casts = [
        'pickup_date' => 'date',
        'reserved_at' => 'datetime',
        'total_amount' => 'decimal:2',
        'items' => 'array', // Cast JSON to array automatically
    ];

    /**
     * Get the customer that owns this reservation
     */
    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class, 'customer_id', 'customer_id');
    }

    public function product(): BelongsTo
    {
        // Since we store product details directly, this relationship is optional
        // Uses the main products table with inventory_type filtering
        return $this->belongsTo(Product::class, 'product_id')->withDefault();
    }

    /**
     * Get the reservation status badge color
     */
    public function getStatusColorAttribute()
    {
        return match($this->status) {
            'pending' => 'bg-yellow-100 text-yellow-800',
            'confirmed' => 'bg-blue-100 text-blue-800', 
            'completed' => 'bg-green-100 text-green-800',
            'cancelled' => 'bg-red-100 text-red-800',
            default => 'bg-gray-100 text-gray-800'
        };
    }

    /**
     * Scope for pending reservations
     */
    public function scopePending($query)
    {
        return $query->where('status', 'pending');
    }

    /**
     * Scope for completed reservations
     */
    public function scopeCompleted($query)
    {
        return $query->where('status', 'completed');
    }

    /**
     * Scope for cancelled reservations
     */
    public function scopeCancelled($query)
    {
        return $query->where('status', 'cancelled');
    }

    /**
     * Check if a customer has any pending reservations
     */
    public static function customerHasPendingReservations($email)
    {
        return static::whereHas('customer', function($query) use ($email) {
                    $query->where('email', $email);
                })
                ->where('status', 'pending')
                ->exists();
    }

    /**
     * Get customer's pending reservations
     */
    public static function getCustomerPendingReservations($email)
    {
        return static::whereHas('customer', function($query) use ($email) {
                    $query->where('email', $email);
                })
                ->where('status', 'pending')
                ->orderBy('created_at', 'desc')
                ->get();
    }

    /**
     * Accessor for backward compatibility - customer_name
     */
    public function getCustomerNameAttribute()
    {
        return $this->customer ? $this->customer->fullname : null;
    }

    /**
     * Accessor for backward compatibility - customer_email
     */
    public function getCustomerEmailAttribute()
    {
        return $this->customer ? $this->customer->email : null;
    }

    /**
     * Accessor for backward compatibility - customer_phone
     */
    public function getCustomerPhoneAttribute()
    {
        return $this->customer ? $this->customer->phone_number : null;
    }
}
